<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Testcase failed]]>
    </line>
  </reporter-output>
  <suite started-at="2020-07-26T18:09:58 IST" name="Data Driven Basics" finished-at="2020-07-26T18:10:06 IST" duration-ms="8526">
    <groups>
    </groups>
    <test started-at="2020-07-26T18:09:58 IST" name="Bank Manager Login Test" finished-at="2020-07-26T18:10:01 IST" duration-ms="3693">
      <class name="com.w2a.testcases.BankManagerLoginTest">
        <test-method signature="loginAsBankManager()[pri:0, instance:com.w2a.testcases.BankManagerLoginTest@4215838f]" started-at="2020-07-26T18:09:58 IST" name="loginAsBankManager" finished-at="2020-07-26T18:10:01 IST" duration-ms="3160" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAsBankManager -->
      </class> <!-- com.w2a.testcases.BankManagerLoginTest -->
    </test> <!-- Bank Manager Login Test -->
    <test started-at="2020-07-26T18:10:01 IST" name="Add Customer Test Case" finished-at="2020-07-26T18:10:06 IST" duration-ms="4791">
      <class name="com.w2a.testcases.AddCustomerTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.w2a.testcases.AddCustomerTest@33352f32]" started-at="2020-07-26T18:09:51 IST" name="setUp" finished-at="2020-07-26T18:09:58 IST" duration-ms="6966" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="addCustomerTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.w2a.testcases.AddCustomerTest@33352f32]" started-at="2020-07-26T18:10:01 IST" name="addCustomerTest" data-provider="dp" finished-at="2020-07-26T18:10:05 IST" duration-ms="3916" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Raman]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Arrora]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[A12354]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Customer added successfully]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed willingly]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed willingly
at org.testng.Assert.fail(Assert.java:97)
at com.w2a.testcases.AddCustomerTest.addCustomerTest(AddCustomerTest.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Testcase failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomerTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.w2a.testcases.AddCustomerTest@33352f32]" started-at="2020-07-26T18:10:06 IST" name="tearDown" finished-at="2020-07-26T18:10:07 IST" duration-ms="688" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.w2a.testcases.AddCustomerTest -->
    </test> <!-- Add Customer Test Case -->
  </suite> <!-- Data Driven Basics -->
</testng-results>
